### ISSUE TITLE
GETENV truncating env.file parameter names

### ISSUE THREAD

**Issue by elderpav** [Deek/CoCoC#9]
When passing the name of an env.file parameter to the function getenv in the CGFX library, the function only reads the first 6 characters of the name. So when you pass, for example, "PALET10" to getenv, it only reads in "PALET1". The function cannot tell the difference between "PALET10" and "PALET1". This means you cannot correctly read in any palette entries from the env.file for palette #'s 10 - 15.

**Comment by Deek** [comment]
Are you sure you're using the CGfx library from CoCoC? The source code I'm looking at, which corresponds to Mike Sweet's "version 7" of cgfx, suggests that it should match up to 13 characters of the name.

**Comment by Deek** [comment]
Sorry, I didn't mean to close the issue.

**Comment by Deek** [comment]
Further information: getenv() is very broken. It only works correctly once at most, because repeated calls leave the previous contents of the (constant) returned string alone. This wouldn't be horrible if it didn't *also* fail to add a terminating nul character to the end of the new string.

Also, it doesn't "work up to 13 characters" -- that was a mistake I made while initially reading the code. It's doing strchr(string, 13) but that means it's looking for '\n' characters.
